### ISSUE TITLE
关于新论坛的 brainstorm

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/CAPUBBS#108]
啊我觉得我们需要把新版论坛 / 报名系统（不管叫什么了吧也许最后实现的东西我们一开始都没想到是啥）的想法搞个 brainstorm 并整理出来～包括不限于实现的功能，框架和技术细节～
嗯但是我不知道用什么形式来 brainstorm

**Comment by zhzhzoo** [comment]
嗯问题 1 是修改 markdown 使它资瓷修改字的颜色

**Comment by JeldorPKU** [comment]
> 嗯问题 1 是修改 markdown 使它资瓷修改字的颜色
> 要不然夏天。那样的帖子就找不到了

@zhzhzoo 确定要用markdown吗？那样我觉得可能需要自己写一个编辑器了。我觉得可能还是现成的比较好呢，因为好像对于许多人，富文本是刚需……我个人是支持纯文本的，比如像知乎那样处理markdown，但是貌似不够友好……

**Comment by JeldorPKU** [comment]
我觉得每个小话题都可以开一个issue，比如编辑器，我想直接支持emoji :smile: 这样就不需要别的表情了～

**Comment by zhzhzoo** [comment]
@JeldorPKU 有现成编辑器我们只要改点儿东西就可以了吧～
关于富文本我觉得好像确实没有特别多需求诶～比如字号一般不用改

**Comment by zhzhzoo** [comment]
@JeldorPKU 那我们直接开个 repo 吧～

**Comment by huxuan** [comment]
谁整理一下这个发到新的 repo 里然后把这个关了吧~

**Comment by JeldorPKU** [comment]
转移到新的repo里面去讨论吧～
