### ISSUE TITLE
关闭借车系统？

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUBBS#138]
现在借车系统好像没有什么用了……大家还在上面求车然而这个还不如水群来得高效……

**Comment by huxuan** [comment]
新版需求里可以加上这个，我还想搞一个论坛大水群来着……其实就是论坛的聊天室呗……

**Comment by JeldorPKU** [comment]
其实我一直没有想好借车这个东西应该如何上线，我觉得其实之前那种模式并不好……

**Comment by huxuan** [comment]
现在的repo是CAPUHOME了嘛，就不能仅仅是BBS啦，什么活动报名系统，借车系统，这些都是慢慢加的，设计的时候考虑到这些后续扩展就好了~需求分析也把能想到的先想到呗~

**Comment by zhzhzoo** [comment]
啊老蒋想删直接删啊。。。

**Comment by JeldorPKU** [comment]
这个已经在 #139 中解决了，关掉了哈
