### ISSUE TITLE
MySQL backup script

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/CAPUBBS#16]
We should backup the mysql regularly, we need a script to do it automatically.

**Comment by QwertyJack** [comment]
yes！！！

**Comment by huxuan** [comment]
@QwertyJack Feel free to add this issue to you. ;-)

**Comment by QwertyJack** [comment]
surely

**Comment by QwertyJack** [comment]
@huxuan done
需要贴代码么， 还是直接close issue？

**Comment by huxuan** [comment]
@QwertyJack We can create a new folder under the root directory and put the mysql backup script there. It's a good idea to include these kind of related scripts into code repo.

**Comment by huxuan** [comment]
Fixed by pull request #65
