### ISSUE TITLE
Use only ONE instance for mysql connection.

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/CAPUBBS#38]

**Comment by zhzhzoo** [comment]
这有点儿麻烦因为入口有一堆。。。

**Comment by huxuan** [comment]
可以新建一个lib（跟config类似）作为公用的部分（如果用框架的话，一般都自带这些功能的……

**Comment by QwertyJack** [comment]
我说也是

**Comment by huxuan** [comment]
@QwertyJack Would you please show me the actual commit message? I don't think the related code has been merged.

**Comment by huxuan** [comment]
Fixed by pull request #64
