### ISSUE TITLE
Drop deprecated mysql_connect.

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/CAPUBBS#39]

**Comment by huxuan** [comment]
Warning
This extension is deprecated as of PHP 5.5.0, and will be removed in the future. Instead, the MySQLi or PDO_MySQL extension should be used. See also MySQL: choosing an API guide and related FAQ for more information. Alternatives to this function include:
mysqli_connect()
PDO::__construct()

Reference: http://php.net/manual/en/function.mysql-connect.php

**Comment by QwertyJack** [comment]
We will use php5 instead of higher ver.

**Comment by huxuan** [comment]
Close as discussed.
