### ISSUE TITLE
Problem parsing the url of users' icons.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUBBS#48]
![screen shot 2015-03-16 at 10 40 35](https://cloud.githubusercontent.com/assets/8514953/6659848/f9ad32ba-cbc8-11e4-8604-94f316d9f547.png)
The icons' url are parsed incorrectly, like this: `http://www.chexie.net/bbsimg/icons/exie.net/bbsimg/pictures/64959716.gif`, which should be: `http://www.chexie.net/bbsimg/pictures/64959716.gif`.

**Comment by zhzhzoo** [comment]
啊 谁看看大斯胸和小刀的 `$userinfo['icon']` 是啥。。。米有数据库呜呜

**Comment by JeldorPKU** [comment]
@zhzhzoo 大师兄的是undefined，小刀的我已经改好了。是数据库里面存储的东西不对，和解析没有关系。

**Comment by zhzhzoo** [comment]
好吧呀囧......

**Comment by huxuan** [comment]
I think this bug is already resolved, isn't it?
Feel free to close this issue if it is.

**Comment by JeldorPKU** [comment]
This problem is now solved.
