### ISSUE TITLE
我来贴几个warning&error

### ISSUE THREAD

**Issue by QwertyJack** [CAPU-ENG/CAPUBBS#62]
[Wed Mar 18 15:03:01.032927 2015] [:error] [pid 13573] [client 61.240.149.149:12799] PHP Notice:  Array to string conversion in /work/capu/CAPUBBS/api/client.php on line 336
[Wed Mar 18 15:07:15.587400 2015] [:error] [pid 13727] [client 218.249.94.11:42513] PHP Fatal error:  Call to a member function xpath() on a non-object in /work/capu/CAPUBBS/bbs/lib/mainfunc.php on line 10, referer: http://182.92.150.205/bbs/main/index.php?bid=1
[Wed Mar 18 17:48:36.675114 2015] [:error] [pid 14849] [client 61.240.149.149:37761] PHP Warning:  opendir(../../bbsimg/icons): failed to open dir: No such file or directory in /work/capu/CAPUBBS/bbs/edituser/index.php on line 217, referer: http://test.chexie.net/bbs/home/information.php
[Wed Mar 18 17:48:36.699647 2015] [:error] [pid 14849] [client 61.240.149.149:37761] PHP Warning:  readdir() expects parameter 1 to be resource, boolean given in /work/capu/CAPUBBS/bbs/edituser/index.php on line 221, referer: http://test.chexie.net/bbs/home/information.php
[Wed Mar 18 17:48:36.711324 2015] [:error] [pid 14849] [client 61.240.149.149:37761] PHP Warning:  closedir() expects parameter 1 to be resource, boolean given in /work/capu/CAPUBBS/bbs/edituser/index.php on line 228, referer: http://test.chexie.net/bbs/home/information.php
[Wed Mar 18 17:48:54.227845 2015] [:error] [pid 15049] [client 61.240.149.149:41188] PHP Warning:  mkdir(): No such file or directory in /work/capu/CAPUBBS/bbs/utils/icon_upload.php on line 14, referer: http://test.chexie.net/bbs/edituser/
[Wed Mar 18 17:48:54.240294 2015] [:error] [pid 15049] [client 61.240.149.149:41188] PHP Warning:  move_uploaded_file(../../bbsimg/icons/user_upload/efc11495965511d18bfd5f1c55e07d403c19a288.png): failed to open stream: No such file or directory in /work/capu/CAPUBBS/bbs/utils/icon_upload.php on line 19, referer: http://test.chexie.net/bbs/edituser/

[Fri Mar 20 09:07:58.918829 2015] [:error] [pid 17530] [client 94.102.53.195:48380] script '/var/www/CAPUBBS/bins.php' not found or unable to stat
[Fri Mar 20 18:31:13.555480 2015] [:error] [pid 16114] [client 23.95.12.210:52137] script '/var/www/CAPUBBS/phpMyAdmin/scripts/setup.php' not found or unable to stat
[Fri Mar 20 21:54:28.589842 2015] [:error] [pid 15406] [client 121.42.0.37:35378] script '/var/www/CAPUBBS/phpMyAdmin/scripts/setup.php' not found or unable to stat, referer: http://182.92.150.205/

**Comment by JeldorPKU** [comment]
我觉得是不是应该发现一下问题再提issue？一堆error贴出来可能有很多不一样的Bug，一个个来吧。

**Comment by QwertyJack** [comment]
ok!
