### ISSUE TITLE
DBconnection--已解决

### ISSUE THREAD

**Issue by QwertyJack** [CAPU-ENG/CAPUBBS#63]
目前我把散落在各处的mysql_connect都统一搁在bbs/lib/mainfuc.php里边了，如需调用数据库只需包含此文件，加一句 dbconnect; 即可。

另外api/client.php与bbs/lib/mainfunc.php有几个函数有命名冲突，已标明。

有几个关于数据库连接的issue可以考虑关闭了。

HAVE FUN !!!

**Comment by huxuan** [comment]
这个不用单独新建一个issue吧？或者你是有什么别的用意么？

**Comment by JeldorPKU** [comment]
@huxuan 你竟然还没睡……这个我和 @QwertyJack 说了，告诉了他使用方法嗯。
