### ISSUE TITLE
Deploy the old bbs to make some old urls accessible.

### ISSUE THREAD

**Issue by goodman-capu** [CAPU-ENG/CAPUBBS#79]
e.g. http://www.chexie.net/cgi-bin/bbs.pl?see=ames&b=4&p=1

**Comment by ckcz123** [comment]
本来我在 /cgi-bin/bbs.pl 中设置了自动跳转的... 
https://github.com/CAPU-ENG/CAPUBBS/blob/master/cgi-bin/bbs.pl

**Comment by zhzhzoo** [comment]
来我们把 bbs.pl 翻译成 php 然后设个 rewrite 吧。。。

**Comment by QwertyJack** [comment]
Now this is done.
Close it plz.

**Comment by huxuan** [comment]
Close as done. Feel free to reopen it if there is any further problems.
