### ISSUE TITLE
求开。。。

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/CAPUBBS#87]
rt

**Comment by zhzhzoo** [comment]
以及验证码咋了。。。

**Comment by zhzhzoo** [comment]
求把之前的 issue 和 pr 开开～

**Comment by huxuan** [comment]
@zhzhzoo Feel free to reopen any issue/pr if you think it's necessary.

Please don't spam the issue list.

Close this issue as it's not useful.

**Comment by zhzhzoo** [comment]
啊 我不能 reopen 不是我自己关掉的 issue 。。。

**Comment by huxuan** [comment]
@zhzhzoo 是没有权限还是？如果是没有权限的话，请说明是哪一个issue

**Comment by zhzhzoo** [comment]
@huxuan 嗯没有权限。。。
是这个～ https://github.com/CAPU-ENG/CAPUBBS/pull/41
抱歉没有说清楚呀。。。

**Comment by huxuan** [comment]
@zhzhzoo Done.
