### ISSUE TITLE
把服务器配置里可以放进 .htaccess 的放进 .htaccess 然后把 .htaccess 放进代码库（？）

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/CAPUBBS#90]
嗯我也不知道是不是一个好的建议。。。
不过这样子应该能让改 rewrite 或者其它什么的人类省不少劲儿～
考虑到有 nginx 党（？） anyway....

**Comment by huxuan** [comment]
可以放啊~

**Comment by QwertyJack** [comment]
基本没必要
* 目前虚拟主机（vhost）几乎零配置，只包含 1. 限速；2. 自定义日志；3. 证书，i.e. 如果须搭建单机环境，之需指定`DocumentRoot`即可
* 关于https的rewrite是letscrypt自动生成的
* nginx和apache的.htaccess不能通用吧？
* .htaccess会降低性能

以上
PS：可关
