### ISSUE TITLE
编辑帖子后 帖子来源会错误

### ISSUE THREAD

**Issue by goodman-capu** [CAPU-ENG/CAPUBBS#91]
比如用客户端发帖 再编辑后 显示的发帖来源就是网页版了。。。

**Comment by huxuan** [comment]
是不是用客户端再编辑就有变成来源是客户端了？

**Comment by goodman-capu** [comment]
不是啊 就是用客户端编辑 编辑完了就不显示来自客户端了...

范志康 | 好男人
北京大学自行车协会
电话 +8618579101828
