### ISSUE TITLE
实名制！！！

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUBBS#95]
建立会员信息库，采集会员的姓名、学号、入会时间、是否暑期队员等等信息。招新时需要出示校园卡，验证学生身份再入会。注册的时候需要输入匹配的姓名学号，验证确实是会员之后才能注册。

**Comment by zhzhzoo** [comment]
嗯是不是跟其它事情一起统筹起来搞～

**Comment by goodman-capu** [comment]
现在的会员注册新号怎么办。。。

**Comment by goodman-capu** [comment]
我觉得 把注册码制度完善，把Bug解决了 这样会好很多 省去很多人工麻烦 老会员也还可以继续使用

**Comment by JeldorPKU** [comment]
昨晚理事会讨论了一下这个还是先放放吧。现在我也说不出这个实名之后的信息有什么用，而且线上报名活动这个事情也不太有谱，还没有想好怎么做，所以我先关掉这个了。如果以后需要再打开吧。

**Comment by zhzhzoo** [comment]
。。。求旁听理事会啊。。。人什么选课签证买股票都可以线上搞啊

**Comment by huxuan** [comment]
老蒋是荣誉理事才旁听的，别闹~
