### ISSUE TITLE
建议危险/重要的字段不要开放出来。

### ISSUE THREAD

**Issue by wangxd18** [CAPU-ENG/CAPUBBS#99]
我是xiaoE。

虽说是开源，也要谨慎些呀。
比如，像`dbconnector`第3行这种关键信息就不要开放了吧……

建议的解决方法：
* 改账号密码，db服务器限定只有localhost或者少数几个内网ip可以访问（视服务器配置而定）。
* 新的账号密码放入静态property文件，该文件加入`.gitignore`中，个中内容不开放传播。
  * 如果property文件需要遵循某种格式要求，可以建一个这种property文件的模板——只给出样例模板，用以说明语法规则，仍不暴露关键字段。

**Comment by huxuan** [comment]
嗯，确实这个安全隐患挺大的，主要整个repo有很多历史遗留问题……
暂时只是限制了mysql只能本地访问……
我来搞个PR先fix掉这个issue吧

**Comment by huxuan** [comment]
等 #101 被merge了之后，找个半夜的时间偷偷上线再改一下数据库密码好了~
Maybe we also need some documents. :-(

**Comment by huxuan** [comment]
@wangxd18 如果对 #101 有任何修改建议请尽管提出来~ :-)

**Comment by wangxd18** [comment]
@huxuan This one should be closed now.
